# Generated by Django 4.1.7 on 2023-02-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tils", "0004_alter_til_author"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="til",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="tils.til",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("til_id", "tag"), name="unique tag on a til"
            ),
        ),
    ]
