# Generated by Django 4.1.7 on 2023-03-03 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tils", "0004_alter_til_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="til",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tils",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
