# Generated by Django 4.1.7 on 2023-02-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("tils", "0002_rename_subject_id_til_subject"),
        ("til_tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TilTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tils",
                        to="tags.tag",
                    ),
                ),
                (
                    "til",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="tils.til",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PostTag",
        ),
    ]
